### ISSUE TITLE
error parsing layer type ReLU index 3

### ISSUE THREAD

**Issue by shiva13425** [lewes6369/tensorRTWrapper#1]
Hi,
I have used the below command in the terminal.
**./install/runYolov3 --caffemodel=data/yolov3.caffemodel --prototxt=data/yolov3.prototxt --input=./1.jpg
./install/runYolov3** 

Environment: 
Jetson TX2, cuda 9.0, tensorrt 4, cudnn7, opencv 3.4.1

Result:
--caffemodel=data/yolov3.caffemodel 
--prototxt=data/yolov3.prototxt 
--input=./1.jpg 
####### input args####### 
C=3;H=416;W=416;caffemodel=data/yolov3.caffemodel;calib=;input=./1.jpg;mode=INT8;prototxt=data/yolov3.prototxt;
init plugin proto: data/yolov3.prototxt caffemodel: data/yolov3.caffemodel
Begin parsing model...
Caffe Parser: ReLU negative slope is not supported
error parsing layer type ReLU index 3
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)

Kindly share your commands ..  Thanks

**Comment by lewes6369** [comment]
Hi, shiva13425. Maybe you changed your ReLU layer name. Make sure that your ReLU layers named as layer1-act , layer2-act ... layer105-act and so on. 

Like this:
`
layer {
    bottom: "layer2-conv"
    top: "layer2-conv"
    name: "layer2-act"
    type: "ReLU"
    relu_param {
        negative_slope: 0.1
    }
}
`

**Comment by lewes6369** [comment]
Or you can modify the 'isLeakyRelu' function in "PluginFactory.h" to your leaky ReLU name which written in your yolov3 prototxt.

**Comment by shiva13425** [comment]
Hi @lewes6369 ,
Thanks for reply. I will go with your suggestion.. 
I will check it. 
Thanks a lot..

**Comment by shiva13425** [comment]
Hi,
I have modified the  "PluginFactory.h" as 
std::regex(R"(ReLU(\d*))")
std::regex(R"(Interp(\d*))")

Result:
./install/runYolov3 
--caffemodel=data/yolov3.caffemodel 
--prototxt=data/yolov3.prototxt 
--input=./1.jpg 
####### input args####### 
C=3;H=416;W=416;caffemodel=data/yolov3.caffemodel;calib=;input=./1.jpg;mode=INT8;prototxt=data/yolov3.prototxt;
init plugin proto: data/yolov3.prototxt caffemodel: data/yolov3.caffemodel
Begin parsing model...
Input:256 13 13
ouputDims:256 26 26
Input:128 26 26
ouputDims:128 52 52
End parsing model...
Segmentation fault (core dumped)

Kindly share your commands. Thanks

**Comment by lewes6369** [comment]
Maybe your outputNames also are different names.  In the "main.cpp" the net will be created 
`
TrtNet net(deployFile,caffemodelFile,
{"layer82-conv","layer94-conv","layer106-conv"},calibData,run_mode);
`
The output layers named as `{"layer82-conv","layer94-conv","layer106-conv"}`, So you should check yours.

Now I commit some codes about "add the outputNodes args". So you can type your output nodes name to the cmd. Likes `--outputNodes="conv1,conv2,conv3"`

And there is a assert where you crashed, you can modify the "wrapper/CMakeLists.txt" `set(CMAKE_BUILD_TYPE Release)` -> `set(CMAKE_BUILD_TYPE Debug)`. Then will output the assert info.

PS:I do not add the yolo layer yet, you should do it by yourself in cpu. This week I will added it.

**Comment by shiva13425** [comment]
Hi @lewes6369 ,
Thanks for the reply. I will check everything you suggested. 
Am awaiting for an update of yolo layer implementation. 
Thanks.

**Comment by lewes6369** [comment]
Hi,@shiva13425 , I implemented the yolo layer on cpu at present. You can have a try.
Thanks.

**Comment by shiva13425** [comment]
Hi @lewes6369 ,
Thanks for the update. Still am stuck with Segmentation fault (core dumped) issue. can you share the yolov3.prototxt and yolov3.caffemodel link so that i can cross varify. Thanks.

**Comment by lewes6369** [comment]
@shiva13425 
Just check the link https://pan.baidu.com/s/1exXKXw7eFIpfBlO3q9VBTQ password: es12  It depends on the official 608-yolov3-cfg.

**Comment by shiva13425** [comment]
Hi @lewes6369,
Thanks a lot..
I have tried to download the files but I couldn't. I have a doubt like is there different models of yolov3 like 608x608, 416x416, 304x304 with corresponding performance. I like to achieve 20+ fps on jetson tx2 with yolov3. Is there any possibility to do that?

**Comment by lewes6369** [comment]
I didn't test in the tx2 yet.But if the 608 size are not meeting your requirements. You can try to check the 416 size. It could be 1.5~2 faster than the 608.
As I know , the jetson tx2 also support the fast float16 mode. And in my testing result, the float16 mode can be much faster than float32 which almost none accuracy loss.
You can have a try, and hope you will achieve the goal.

Thanks.

**Comment by lewes6369** [comment]
Addition,If you have smaller classes of objects to detect. The param can be smaller so that faster in the inference.

**Comment by shiva13425** [comment]
Hi @lewes6369 ,
Thanks for the suggestion. I will test everything on jetson tx2. Then can you suggest a best way to reduce number of classes to be detected.
Thank you.

**Comment by lewes6369** [comment]
It depends what you want to detect in your labels for training.
The simplest way is just to reduce the ouputNums of output convolution nodes to the '3*(1+4+classnum)' in yolo layers.For the more, you can reduce the other convolution outputs num and do finetune. It may be not good enough in accuracy but have an improvement in speed.
Thanks.

**Comment by shiva13425** [comment]
Hi @lewes6369 ,
Thanks for the suggestion. 
[yolov3_416 (copy).prototxt.txt](https://github.com/lewes6369/tensorRTWrapper/files/2698134/yolov3_416.copy.prototxt.txt)
Here I have uploaeded the yolov3 prototxt kindly suggest the output layers. Because am facing Segmentation fault.  
Thank you.

**Comment by slayerlpj** [comment]
./install/runYolov3 --caffemodel=./yolov3_608.caffemodel --prototxt=./yolov3_608.prototxt --input=./test.jpg --W=608 --H=608 --class=80

Caffe Parser: ReLU negative slope is not supported
error parsing layer type ReLU index 3
ERROR: ssd_error_log: Fail to parse

This is my prototxt file.
[yolov3_608_trt.prototxt.tar.gz](https://github.com/lewes6369/tensorRTWrapper/files/2698363/yolov3_608_trt.prototxt.tar.gz)
How can i fixed  the issue ？

**Comment by slayerlpj** [comment]
Hi @lewes6369 .
Begin parsing model...
Caffe Parser: ReLU negative slope is not supported
error parsing layer type ReLU index 3
ERROR: ssd_error_log: Fail to parse

This is my prototxt file 
[yolov3_608_trt.prototxt.tar.gz](https://github.com/lewes6369/tensorRTWrapper/files/2698373/yolov3_608_trt.prototxt.tar.gz)
How can I fix the issue ?
thank you.

**Comment by lewes6369** [comment]
@shiva13425 Your prototxt layer is so strange , I can not read it clear. It seems that the upsample layer is implemented by "python" layer not by "upsample". And the other bn,scale are also named by only nums which can not recognized by the repo code.
Your prototxt may not be used here. How did you train or convert it?

**Comment by lewes6369** [comment]
Hi，@slayerlpj 
Your prototxt seems ok.
you can uncomment the cout sentence in "isPluginExt" in PluginFactory.h  , and add cout in  "createPlugin" of "isLeakyRelu" conditions .

Then you can run the program to check your layer name,and find whether the layer is recognized as LeakyRelu.

You can print the console here. I will also have a check.

**Comment by slayerlpj** [comment]
@lewes6369 
Begin parsing model...
check plugin layer1-conv
check plugin layer1-bn
check plugin layer1-scale
check plugin layer1-act
Caffe Parser: ReLU negative slope is not supported
error parsing layer type ReLU index 3
ERROR: ssd_error_log: Fail to parse
This is my cout, I add a print as you told me but I can't get in the function "createPlugin(const char* layerName, const void* serialData, size_t serialLength)"

**Comment by shiva13425** [comment]
Hi @slayerlpj,
Kindly go through the comments from the first. You will get the solution.

**Comment by shiva13425** [comment]
Hi @slayerlpj
can you share the model you are using now.(corresponding to the prototxt you shared) . My email id : sivakumar17081992@gmail.com

**Comment by shiva13425** [comment]
@lewes6369 I have just downloaded it from https://github.com/eric612/MobileNet-YOLO. Can you share the caffemodel and prototxt which you are using. so that I can test it here.
My mail ID: sivakumar17081992@gmail.com

**Comment by shiva13425** [comment]
@lewes6369 Am trying to use mobilenet_yolov3_lite_deploy.caffemodel & mobilenet_yolov3_lite_deploy.prototxt
Result:
Begin parsing model...
could not parse layer type DepthwiseConvolution
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)
Kindly share your comments .
Thanks

**Comment by slayerlpj** [comment]
Hi @shiva13425 I have sent my model to you and I have solved this problem.

**Comment by slayerlpj** [comment]
Hi @lewes6369 I have solved this problem.Now I can run the program.
Thank you !!!

**Comment by shiva13425** [comment]
@slayerlpj 
Thanks for sharing the files.
1. I have removed "negative_slope: 0.1" from prototxt to avoid this error "Caffe Parser: ReLU negative slope is not supported"
2. Now I got this error "could not parse layer type Upsample" 
Kindly share your comments. Hope you have come across these errors.
Thanks.

**Comment by lewes6369** [comment]
Hi, @slayerlpj  So what is the reason about that problem?

**Comment by lewes6369** [comment]
@shiva13425 I reupload the model [here](https://pan.baidu.com/s/1gPzM8yBwjPkqPTHfFolXhQ) pw: jig3
the negative_slope do not need to remove. It is because your leakyRelu layers are not recognized as plugin. You should check  https://github.com/lewes6369/tensorRTWrapper/issues/1#issuecomment-444445053 and https://github.com/lewes6369/tensorRTWrapper/issues/1#issuecomment-444512783

You must check the layer names not the type is in the pattern written in "PluginFactory.h"

**Comment by shiva13425** [comment]
@lewes6369 
[error.txt](https://github.com/lewes6369/tensorRTWrapper/files/2714126/error.txt)
  
I have modified the PluginFactory.h so that parsing model is done. I hope the issue with output node or the model am using. Here I have attached the error as text  file. Kindly share your comments. 

Note : Am unable to download the model from the link you shared. So if possible can you share model and prototxt through mail. (sivakumar17081992@gmail.com). so that I can try with your model and prototxt to confirm whether the issue with model.

Thank you

**Comment by lewes6369** [comment]
HI,@shiva13425, sorry for reply late. I read the file log ,and find that you modified the output node, removing one output node.You may need to keep the three nodes or change the source codes.
the output Nodes should be --outputNodes= layer82-conv,layer94-conv,layer106-conv 
but you typed as layer87-conv, layer99-conv.

The more, In the new version I added the yolo layer in tensorRT so that it can run the whole pipeline more faster.  Check git [here](https://github.com/lewes6369/TensorRT-Yolov3)

I have to close the issue . It is far more than the repo topic.

**Comment by lewes6369** [comment]
@shiva13425  I have sent your model, please take a look.

**Comment by shiva13425** [comment]
@lewes6369 Thanks for your valuable time. I will work on the model you shared. Thanks for your support.
