### ISSUE TITLE
Why only accept batch size = 1?

### ISSUE THREAD

**Issue by xmfbit** [lewes6369/tensorRTWrapper#5]
Why only `batch_size = 1` is allowed in the plugin code? For example: https://github.com/lewes6369/tensorRTWrapper/blob/master/code/src/UpsampleLayer.cu#L52

```
  int UpsampleLayerPlugin::enqueue(int batchSize, const void*const * inputs, void** outputs, void* workspace, cudaStream_t stream)
  {
      assert(batchSize == 1);
     // XXX
```

**Comment by lewes6369** [comment]
Hi,@xmfbit . I'm sorry that I just test for batchSize of 1. If you want to apply in some batches, some copy code and pre-post code need to modify.
