### ISSUE TITLE
Support for TensorRT4

### ISSUE THREAD

**Issue by NengQian** [lewes6369/tensorRTWrapper#7]
Hi @lewes6369 , this is a really great work. I have tried your wrapper on my jetson xavier board, it works very well.
However, when I tried it on my jetson Tx2 board, whose latest version of TensorRT is 4, it then cannot be compiled.
The error messages show that in YoloLayer.h, you tried to inherit IPluginExt class, which does not exist in Nvinfer.h in TensorRT4. Also in YoloLayer.cu line 84, you return Dims3, which does either not exist in tensorRT4.

My jetson tx2 work environment is ubuntu 16.04+cuda 9.0+tensorRT 4.0.4-1.
Do you have any version of your wrapper which supports this environment?

Thank you very much.

**Comment by lewes6369** [comment]
I am sorry. Recently I have no plan to the implement the version below version 4. If you used 4.0.4, it should including the interfaces in 4.0.1.6.
If it does not work , maybe you have to migrate the code to your board TR version.

**Comment by NengQian** [comment]
Hi I mistake the version of tensorRT and the version of Nvinfer API. The version of Nvinfer API was 4.0.4-1, but then the actually tensorRT version was 3. 
So after I update my tensorRT to version 4, it works well.
Thank you.
